/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account_account_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Onboarding */
        get: operations["get_onboarding_account_onboarding_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/onboarding/self-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Self Profile
         * @description Create the account's `self` profile, or reuse it when onboarding resumes.
         */
        put: operations["put_self_profile_account_onboarding_self_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Appointment */
        post: operations["create_appointment_appointments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{appointment_id}/checklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Appointment Checklist */
        get: operations["get_appointment_checklist_appointments__appointment_id__checklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{appointment_id}/checklist/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Appointment Checklist */
        post: operations["generate_appointment_checklist_appointments__appointment_id__checklist_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{appointment_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Appointment Review */
        post: operations["create_appointment_review_appointments__appointment_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extraction/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Extraction Job */
        get: operations["get_extraction_job_extraction_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extraction/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_extraction_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extraction/jobs/{job_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Job */
        post: operations["run_job_extraction_jobs__job_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestions/camera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Camera Capture */
        post: operations["upload_camera_capture_ingestions_camera_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestions/direct-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Direct File */
        post: operations["upload_direct_file_ingestions_direct_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestions/{ingestion_id}/assignment/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Ingestion */
        post: operations["assign_ingestion_ingestions__ingestion_id__assignment__profile_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestions/{ingestion_id}/extraction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion Extraction */
        get: operations["get_ingestion_extraction_ingestions__ingestion_id__extraction_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_profiles_get"];
        put?: never;
        /** Create Profile */
        post: operations["create_profile_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_profiles__profile_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profile_id}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Aliases */
        get: operations["get_profile_aliases_profiles__profile_id__aliases_get"];
        /** Put Profile Aliases */
        put: operations["put_profile_aliases_profiles__profile_id__aliases_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profile_id}/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Appointments */
        get: operations["list_appointments_profiles__profile_id__appointments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profile_id}/attested-conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Declare Attested Conditions */
        put: operations["declare_attested_conditions_profiles__profile_id__attested_conditions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profile_id}/attested-medications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Declare Attested Medications */
        put: operations["declare_attested_medications_profiles__profile_id__attested_medications_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profile_id}/health-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile Health Context
         * @description Return the latest reported age and weight so a resumed session can show them.
         */
        get: operations["get_profile_health_context_profiles__profile_id__health_context_get"];
        put?: never;
        /** Create Profile Health Context */
        post: operations["create_profile_health_context_profiles__profile_id__health_context_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profile_id}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Memory */
        get: operations["get_memory_profiles__profile_id__memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{profile_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Records */
        get: operations["list_records_profiles__profile_id__records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Record */
        get: operations["get_record_records__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{record_id}/extraction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Record Extraction */
        get: operations["get_record_extraction_records__record_id__extraction_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{record_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Review Record Extraction */
        patch: operations["review_record_extraction_records__record_id__review_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountRead */
        AccountRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Onboarding Status */
            onboarding_status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AppointmentCreate */
        AppointmentCreate: {
            /** Clinician Name */
            clinician_name?: string | null;
            /** Location */
            location?: string | null;
            /** Profile Id */
            profile_id: string;
            /** Reason */
            reason?: string | null;
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
        };
        /** AppointmentRead */
        AppointmentRead: {
            /** Clinician Name */
            clinician_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Location */
            location: string | null;
            /** Profile Id */
            profile_id: string;
            /** Reason */
            reason: string | null;
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
            /** Status */
            status: string;
        };
        /** AppointmentReviewCreate */
        AppointmentReviewCreate: {
            /** Stars */
            stars: number;
        };
        /** AppointmentReviewRead */
        AppointmentReviewRead: {
            /** Appointment Id */
            appointment_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Stars */
            stars: number;
        };
        /** AttestedEntry */
        AttestedEntry: {
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Title */
            title: string;
        };
        /** AttestedMemoryRead */
        AttestedMemoryRead: {
            /** Category */
            category: string;
            /**
             * Declared At
             * Format: date-time
             */
            declared_at: string;
            /** Facts */
            facts: components["schemas"]["MemoryFactRead"][];
        };
        /**
         * AttestedMemoryUpdate
         * @description The complete current set. An empty list declares that there are none.
         */
        AttestedMemoryUpdate: {
            /** Entries */
            entries?: components["schemas"]["AttestedEntry"][];
        };
        /** Body_upload_camera_capture_ingestions_camera_post */
        Body_upload_camera_capture_ingestions_camera_post: {
            /** Display Filename */
            display_filename?: string | null;
            /** Provisional Profile Id */
            provisional_profile_id?: string | null;
            /** Uploads */
            uploads: string[];
            /** User Context */
            user_context?: string | null;
        };
        /** Body_upload_direct_file_ingestions_direct_file_post */
        Body_upload_direct_file_ingestions_direct_file_post: {
            /** Display Filename */
            display_filename?: string | null;
            /** Provisional Profile Id */
            provisional_profile_id?: string | null;
            /** Uploads */
            uploads: string[];
            /** User Context */
            user_context?: string | null;
        };
        /** ChecklistItemRead */
        ChecklistItemRead: {
            /** Appointment Id */
            appointment_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Is Generic */
            is_generic: boolean;
            /** Question */
            question: string;
            /** Source Fact Id */
            source_fact_id: string | null;
        };
        /** DocumentMetadataCandidateRead */
        DocumentMetadataCandidateRead: {
            /** Attempt Id */
            attempt_id: string;
            /** Confidence */
            confidence: number;
            /** Id */
            id: string;
            /** Metadata Type */
            metadata_type: string;
            /** Original Value */
            original_value: {
                [key: string]: unknown;
            };
            /** Record Id */
            record_id: string | null;
            /** Review Status */
            review_status: string;
            /** Submitted Value */
            submitted_value: {
                [key: string]: unknown;
            } | null;
        };
        /** ExtractionAttemptRead */
        ExtractionAttemptRead: {
            /** Attempt Number */
            attempt_number: number;
            /** Failure Code */
            failure_code: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Internal Phase */
            internal_phase: string | null;
            /** Job Id */
            job_id: string;
            /** Processing Method */
            processing_method: string | null;
            /** Provider */
            provider: string;
            /** Provider Components */
            provider_components: {
                [key: string]: unknown;
            };
            /** Routing Reason */
            routing_reason: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
        };
        /** ExtractionJobRead */
        ExtractionJobRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Phase */
            current_phase: string | null;
            /** Failure Code */
            failure_code: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Ingestion Id */
            ingestion_id: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** ExtractionRead */
        ExtractionRead: {
            /** Assignment History */
            assignment_history: components["schemas"]["IngestionAssignmentRead"][];
            /** Attempts */
            attempts: components["schemas"]["ExtractionAttemptRead"][];
            ingestion: components["schemas"]["IngestionRead"];
            /** Jobs */
            jobs: components["schemas"]["ExtractionJobRead"][];
            /** Memory Candidates */
            memory_candidates: components["schemas"]["MemoryCandidateRead"][];
            /** Metadata Candidates */
            metadata_candidates: components["schemas"]["DocumentMetadataCandidateRead"][];
            /** Observations */
            observations: components["schemas"]["MetricObservationRead"][];
            /** Patient Evidence */
            patient_evidence: components["schemas"]["PatientEvidenceRead"][];
            record: components["schemas"]["MedicalRecordRead"] | null;
            /** Source References */
            source_references: components["schemas"]["SourceReferenceRead"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestionAssignmentRead */
        IngestionAssignmentRead: {
            /** Attempt Id */
            attempt_id: string;
            /** Candidate Profile Ids */
            candidate_profile_ids: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Id */
            id: string;
            /** Match Version */
            match_version: string;
            /** Method */
            method: string;
            /** Profile Id */
            profile_id: string | null;
        };
        /** IngestionPartRead */
        IngestionPartRead: {
            /** Detected Mime Type */
            detected_mime_type: string;
            /** Id */
            id: string;
            /** Ingestion Id */
            ingestion_id: string;
            /** Ordinal */
            ordinal: number;
            /** Original Filename */
            original_filename: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** IngestionRead */
        IngestionRead: {
            /** Assignment State */
            assignment_state: string;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Filename */
            display_filename: string | null;
            /** Extraction State */
            extraction_state: string;
            /** Id */
            id: string;
            /** Provisional Profile Id */
            provisional_profile_id: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Resolved Profile Id */
            resolved_profile_id: string | null;
            /** Review State */
            review_state: string;
            /** Source Channel */
            source_channel: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Upload State */
            upload_state: string;
            /** User Context */
            user_context: string | null;
        };
        /** IngestionUploadResult */
        IngestionUploadResult: {
            extraction_job: components["schemas"]["ExtractionJobRead"] | null;
            ingestion: components["schemas"]["IngestionRead"];
            /** Parts */
            parts: components["schemas"]["IngestionPartRead"][];
            record: components["schemas"]["MedicalRecordRead"] | null;
        };
        /** MedicalRecordRead */
        MedicalRecordRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Filename */
            display_filename: string;
            /** Id */
            id: string;
            /** Ingestion Id */
            ingestion_id: string;
            /** Issuer Name */
            issuer_name: string | null;
            /** Profile Id */
            profile_id: string;
            /** Record Date */
            record_date: string | null;
            /** Record Type */
            record_type: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MemoryCandidateRead */
        MemoryCandidateRead: {
            /** Attempt Id */
            attempt_id: string;
            /** Confidence */
            confidence: number;
            /** Exact Condition Text */
            exact_condition_text: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Original Value */
            original_value: {
                [key: string]: unknown;
            };
            /** Record Id */
            record_id: string | null;
            /** Review Status */
            review_status: string;
            /** Submitted Value */
            submitted_value: {
                [key: string]: unknown;
            } | null;
            /** Subtype */
            subtype: string;
        };
        /** MemoryFactRead */
        MemoryFactRead: {
            /** Category */
            category: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Profile Id */
            profile_id: string;
            /** Provenance */
            provenance: string;
            /** Source Candidate Id */
            source_candidate_id: string | null;
            /** Source Record Id */
            source_record_id: string | null;
            /** Source Reference Id */
            source_reference_id: string | null;
            /** Title */
            title: string;
        };
        /** MemoryRead */
        MemoryRead: {
            /** Facts */
            facts: components["schemas"]["MemoryFactRead"][];
            profile: components["schemas"]["ProfileRead"];
        };
        /** MetricObservationRead */
        MetricObservationRead: {
            /** Attempt Id */
            attempt_id: string;
            /** Body System */
            body_system: string | null;
            /** Confidence */
            confidence: number;
            /** Flag */
            flag: string | null;
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Label */
            label: string;
            /** Metric Identity */
            metric_identity: string;
            /** Normalized Unit */
            normalized_unit: string | null;
            /** Normalized Value */
            normalized_value: {
                [key: string]: unknown;
            } | null;
            /** Observed On */
            observed_on: string | null;
            /** Original Unit */
            original_unit: string | null;
            /** Original Value */
            original_value: {
                [key: string]: unknown;
            };
            /** Profile Id */
            profile_id: string | null;
            /** Quality State */
            quality_state: string;
            /** Record Id */
            record_id: string | null;
            /** Reference Range */
            reference_range: {
                [key: string]: unknown;
            } | null;
        };
        /** OnboardingRead */
        OnboardingRead: {
            /** Completed Steps */
            completed_steps: string[];
            /** Next Step */
            next_step: string | null;
            self_profile: components["schemas"]["ProfileRead"] | null;
            /** Status */
            status: string;
        };
        /** PatientEvidenceRead */
        PatientEvidenceRead: {
            /** Attempt Id */
            attempt_id: string;
            /** Confidence */
            confidence: number;
            /** Date Of Birth */
            date_of_birth: string | null;
            /** Extracted Name */
            extracted_name: string;
            /** Id */
            id: string;
            /** Ingestion Id */
            ingestion_id: string;
            /** Patient Identifier */
            patient_identifier: string | null;
        };
        /** ProfileAliasRead */
        ProfileAliasRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Profile Id */
            profile_id: string;
        };
        /** ProfileAliasesUpdate */
        ProfileAliasesUpdate: {
            /** Aliases */
            aliases: string[];
        };
        /** ProfileCreate */
        ProfileCreate: {
            /** Display Name */
            display_name: string;
            /**
             * Relationship
             * @default self
             */
            relationship: string;
            /** Sex */
            sex?: string | null;
        };
        /** ProfileHealthContextCreate */
        ProfileHealthContextCreate: {
            /** Age Reported At */
            age_reported_at?: string | null;
            /** Entered Weight */
            entered_weight?: number | string | null;
            /** Reported Age */
            reported_age?: number | null;
            /** Weight Reported At */
            weight_reported_at?: string | null;
            /** Weight Unit */
            weight_unit?: ("kg" | "lb") | null;
        };
        /** ProfileHealthContextRead */
        ProfileHealthContextRead: {
            /** Age Reported At */
            age_reported_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entered Weight */
            entered_weight: string | null;
            /** Id */
            id: string;
            /** Normalized Weight Kg */
            normalized_weight_kg: string | null;
            /** Profile Id */
            profile_id: string;
            /** Reported Age */
            reported_age: number | null;
            /** Weight Reported At */
            weight_reported_at: string | null;
            /** Weight Unit */
            weight_unit: string | null;
        };
        /**
         * ProfileHealthContextSummary
         * @description The latest reported age and weight, with a non-blocking refresh prompt.
         */
        ProfileHealthContextSummary: {
            /** Age Refresh Due */
            age_refresh_due: boolean;
            /** Age Reported At */
            age_reported_at: string | null;
            /** Entered Weight */
            entered_weight: string | null;
            /** Normalized Weight Kg */
            normalized_weight_kg: string | null;
            /** Profile Id */
            profile_id: string;
            /** Reported Age */
            reported_age: number | null;
            /** Weight Refresh Due */
            weight_refresh_due: boolean;
            /** Weight Reported At */
            weight_reported_at: string | null;
            /** Weight Unit */
            weight_unit: string | null;
        };
        /** ProfileRead */
        ProfileRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /** Relationship */
            relationship: string;
            /** Sex */
            sex: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RecordReviewRequest */
        RecordReviewRequest: {
            /** Decisions */
            decisions: components["schemas"]["ReviewCandidateDecision"][];
        };
        /** ReviewCandidateDecision */
        ReviewCandidateDecision: {
            /**
             * Action
             * @enum {string}
             */
            action: "confirm" | "edit" | "ignore";
            /** Candidate Id */
            candidate_id: string;
            /**
             * Candidate Type
             * @enum {string}
             */
            candidate_type: "metadata" | "memory";
            /** Value */
            value?: {
                [key: string]: unknown;
            } | null;
        };
        /** SelfProfileUpdate */
        SelfProfileUpdate: {
            /** Display Name */
            display_name: string;
            /** Sex */
            sex?: string | null;
        };
        /** SourceReferenceRead */
        SourceReferenceRead: {
            /** Bounding Polygon */
            bounding_polygon: unknown[];
            /** Id */
            id: string;
            /** Logical Page */
            logical_page: number;
            /** Memory Candidate Id */
            memory_candidate_id: string | null;
            /** Metadata Candidate Id */
            metadata_candidate_id: string | null;
            /** Metric Observation Id */
            metric_observation_id: string | null;
            /** Native Word Ids */
            native_word_ids: unknown[] | null;
            /** Part Id */
            part_id: string;
            /** Patient Evidence Id */
            patient_evidence_id: string | null;
            /** Text Span */
            text_span: string;
            /** Textract Block Ids */
            textract_block_ids: unknown[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_account_account_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
        };
    };
    get_onboarding_account_onboarding_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingRead"];
                };
            };
        };
    };
    put_self_profile_account_onboarding_self_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelfProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_appointment_appointments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_appointment_checklist_appointments__appointment_id__checklist_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_appointment_checklist_appointments__appointment_id__checklist_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_appointment_review_appointments__appointment_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentReviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_extraction_job_extraction_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_extraction_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_job_extraction_jobs__job_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    upload_camera_capture_ingestions_camera_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_camera_capture_ingestions_camera_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionUploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_direct_file_ingestions_direct_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_direct_file_ingestions_direct_file_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionUploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_ingestion_ingestions__ingestion_id__assignment__profile_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingestion_id: string;
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicalRecordRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingestion_extraction_ingestions__ingestion_id__extraction_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"][];
                };
            };
        };
    };
    create_profile_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_aliases_profiles__profile_id__aliases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileAliasRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_profile_aliases_profiles__profile_id__aliases_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileAliasesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileAliasRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_appointments_profiles__profile_id__appointments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    declare_attested_conditions_profiles__profile_id__attested_conditions_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttestedMemoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttestedMemoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    declare_attested_medications_profiles__profile_id__attested_medications_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttestedMemoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttestedMemoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_health_context_profiles__profile_id__health_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileHealthContextSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_profile_health_context_profiles__profile_id__health_context_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileHealthContextCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileHealthContextRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_profiles__profile_id__memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_records_profiles__profile_id__records_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicalRecordRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_records__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicalRecordRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_extraction_records__record_id__extraction_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_record_extraction_records__record_id__review_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
